services:
  # Application react frontend 
  melodix-app:
    build: ./melodix-client
    container_name: melodix-music-app
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./melodix-client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
  # application backend express.js
  server:
    build:
      context: ./melodix-server
      dockerfile: dockerfile
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - 3000:3000
    command: node index.js
